<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $harvests = \App\Models\Harvest::with('harvestOperation')->get();
        $traders = \App\Models\Trader::all();
        $boxes = \App\Models\Box::all();

        if ($harvests->isEmpty() || $traders->isEmpty() || $boxes->isEmpty()) {
            $this->command->warn('Missing prerequisites (Harvests, Traders, or Boxes).');

            return;
        }

        // Use the first trader for all orders to ensure they get grouped into one SalesOrder for demo
        $trader = $traders->first();

        foreach ($harvests as $harvest) {
            // Create exactly 1 order per harvest to avoid unique constraint issues
            // (assuming constraint might still be present)

            $order = \App\Models\Order::firstOrCreate(
                [
                    'harvest_id' => $harvest->id,
                    'harvest_operation_id' => $harvest->harvest_operation_id,
                ],
                [
                    'trader_id' => $trader->id,
                    'date' => $harvest->harvest_date ?? now(),
                    'notes' => 'Generated by OrderSeeder',
                ]
            );

            // Add Items if not exists
            if ($order->items()->count() == 0) {
                $itemCount = rand(1, min(4, $boxes->count()));
                $selectedBoxes = $boxes->random($itemCount);

                foreach ($selectedBoxes as $box) {
                    $quantity = rand(10, 50);
                    $weight = rand(20, 25); // kg per box

                    \App\Models\OrderItem::create([
                        'order_id' => $order->id,
                        'box_id' => $box->id,
                        'quantity' => $quantity,
                        'weight_per_box' => $weight,
                        // total_weight is auto-calc by model
                    ]);
                }
            }
        }

        $this->command->info('Orders seeded successfully.');
    }
}
